/*
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.</p>
*/

#include <iostream>

int main()
{
    long unsigned sum{2};
    long unsigned n0{3};
    long unsigned n1{5};

    while (n1 < 4'000'000)
    {
        long unsigned n2{n0 + n1};
        n0 = n1;
        n1 = n2;
        if ((n2 % 2) == 0)
        {
            sum += n2;
        }
    }

    std::cout << sum << std::endl;
}